import {
  AaveV3Arbitrum,
  AaveV3Avalanche,
  AaveV3Base,
  AaveV3BNB,
  AaveV3Celo,
  AaveV3Ethereum,
  AaveV3EthereumEtherFi,
  AaveV3EthereumHorizon,
  AaveV3EthereumLido,
  AaveV3Gnosis,
  AaveV3InkWhitelabel,
  AaveV3Linea,
  AaveV3Metis,
  AaveV3Optimism,
  AaveV3Plasma,
  AaveV3Polygon,
  AaveV3Scroll,
  AaveV3Sonic,
  AaveV3ZkSync,
} from '@bgd-labs/aave-address-book';

export enum AaveInstanceType {
  CORE = 'Core',
  PRIME = 'Prime',
  ETHERFI = 'EtherFi',
  HORIZON_RWA = 'Horizon RWA',
}

export const aaveInstanceEntries = {
  AaveV3Arbitrum: AaveV3Arbitrum,
  AaveV3Avalanche: AaveV3Avalanche,
  AaveV3Base: AaveV3Base,
  AaveV3BNB: AaveV3BNB,
  AaveV3Celo: AaveV3Celo,
  AaveV3Ethereum: AaveV3Ethereum,
  AaveV3EthereumEtherFi: AaveV3EthereumEtherFi,
  AaveV3EthereumLido: AaveV3EthereumLido,
  AaveV3Gnosis: AaveV3Gnosis,
  AaveV3InkWhitelabel: AaveV3InkWhitelabel,
  AaveV3Linea: AaveV3Linea,
  AaveV3Metis: AaveV3Metis,
  AaveV3Optimism: AaveV3Optimism,
  AaveV3Plasma: AaveV3Plasma,
  AaveV3Polygon: AaveV3Polygon,
  AaveV3Scroll: AaveV3Scroll,
  AaveV3Sonic: AaveV3Sonic,
  AaveV3ZkSync: AaveV3ZkSync,
  AaveV3EthereumHorizon: AaveV3EthereumHorizon,
} as const;
